### ISSUE TITLE
User can search up characters

### ISSUE THREAD

**Issue by lol-ray** [lol-ray/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can search up characters.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Clicking on the search bar will bring up a solid gray background with all character cards on display. As the user types, the character cards will update to match the current query.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Home Page](https://user-images.githubusercontent.com/110205973/193356156-d67f4a02-be83-429d-8b3d-a6cbc9c6f486.png)
![Search Page](https://user-images.githubusercontent.com/110205973/193356166-dcdfb7e0-e9b5-4a00-9b08-33d347bacd6b.png)
![Search Page - Action](https://user-images.githubusercontent.com/110205973/193356168-cbce02e3-567c-4725-89ae-6aec1efd1f34.png)
![Mobile Home Page](https://user-images.githubusercontent.com/110205973/193356390-709d7e33-b187-477a-8a5b-b7b5af7a3446.png)
![Mobile Search Page](https://user-images.githubusercontent.com/110205973/193356395-f8fc86ad-a251-4c58-a675-7b9f972e4292.png)
![Mobile Search Page - Action](https://user-images.githubusercontent.com/110205973/193356398-e961452d-d788-4cf9-9b39-d2d054b94633.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create HTML skeleton for home page and navigation bar.
- [x] Apply CSS styling to match home page wireframe.
- [x] Create background change when search bar is clicked.
- [ ] Create character cards and display them on search page.
- [ ] Implement live search.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
