### ISSUE TITLE
User can view character information

### ISSUE THREAD

**Issue by lol-ray** [lol-ray/ajax-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view character information.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Clicking on a character card will open up a character page with information displays.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Desktop Character Page](https://user-images.githubusercontent.com/110205973/193357902-e241fa10-ae77-40d8-a571-e7608c4f4f04.png)
![Mobile Character Page](https://user-images.githubusercontent.com/110205973/193357922-566c54bf-bf6e-4607-ba79-087336374ba0.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Create a complete character page.
- [ ] Upon character card click:
  - [ ] Hide character cards.
  - [ ] Clear search bar and shrink it back to normal size.
  - [ ] Display character page.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
